services:
  api:
    build: .
    pull_policy: build
    container_name: fastapi_blog
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
